In [ ]:
pip install transformers

In [ ]:
pip install datasets

In [ ]:
pip install KeywordMasking

In [ ]:
from transformers import AutoTokenizer

model_ckpt = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

In [5]:
from KeywordMasking import DataCollatorForKeywordMasking

example_keywords = ['coronavirus', 'jump']
data_collator = DataCollatorForKeywordMasking(tokenizer=tokenizer,
                                              list_of_keywords=example_keywords,
                                              mlm_probability=0.75,
                                              return_tensors='np')

In [6]:
import pandas as pd

example_text = 'Tokyo reports 143 new coronavirus cases, highest jump in one day: governor.'

inputs = tokenizer(example_text, return_tensors='np')
outputs = data_collator([{"input_ids": inputs["input_ids"][0]}])
pd.DataFrame({
    "original tokens": tokenizer.convert_ids_to_tokens(inputs["input_ids"][0]),
    "masked tokens": tokenizer.convert_ids_to_tokens(outputs["input_ids"][0]),
    "original input ids": inputs["input_ids"][0],
    "masked input ids": outputs["input_ids"][0],
    "labels": outputs["labels"][0]
}).T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
original tokens,[CLS],tokyo,reports,143,new,corona,##virus,cases,",",highest,jump,in,one,day,:,governor,.,[SEP]
masked tokens,[CLS],tokyo,reports,143,new,[MASK],[MASK],cases,",",highest,##age,in,one,day,:,governor,.,[SEP]
original input ids,101,5522,4311,16065,2047,21887,23350,3572,1010,3284,5376,1999,2028,2154,1024,3099,1012,102
masked input ids,101,5522,4311,16065,2047,103,103,3572,1010,3284,4270,1999,2028,2154,1024,3099,1012,102
labels,-100,-100,-100,-100,-100,21887,23350,-100,-100,-100,5376,-100,-100,-100,-100,-100,-100,-100